[package]
name = "brinkc"
version = "0.1.0"
authors = ["Damian Koski <daouki97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
